const path = require('path')
const fs = require('fs')
const envFile = fs.readFileSync(path.join(__dirname, '.env.local'), 'utf8')
for (const line of envFile.split('\n')) {
  const m = line.match(/^([^#=]+)=(.*)$/)
  if (m) process.env[m[1].trim()] = m[2].trim()
}
const { createClient } = require('@supabase/supabase-js')
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)

const dishes = [
  // ===== GUJARATI (20) =====
  { slug:'dhokla', name:'Dhokla', hi:'ढोकला', mr:'ढोकला', c:'gujarati', v:true, m:['breakfast','lunch'], cal:180, acc:null, d:'easy', p:20, ck:20, desc:'Steamed fermented gram flour cake, light and spongy with a mustard-curry leaf tempering.', ings:'Besan:1:cup,Yogurt:0.5:cup,Turmeric powder:0.25:tsp,Eno fruit salt:1:tsp,Green chillies:2:pieces,Mustard seeds:1:tsp,Curry leaves:8:pieces,Sugar:1:tsp,Oil:2:tbsp,Water:0.5:cup,Salt:1:tsp', steps:'Mix besan, yogurt, turmeric, salt and water into smooth batter|Add eno, mix quickly and pour into greased plate|Steam for 15 minutes until toothpick comes clean|Temper mustard seeds, curry leaves in oil with sugar|Pour tempering over dhokla, cut into pieces' },
  { slug:'undhiyu', name:'Undhiyu', hi:'उंधियू', mr:'उंधियू', c:'gujarati', v:true, m:['lunch','dinner'], cal:340, acc:'roti', d:'hard', p:30, ck:45, desc:'A festive Gujarati mixed vegetable casserole with yam, banana, beans, and fenugreek dumplings.', ings:'Yam:200:g,Raw banana:2:pieces,Potato:2:pieces,Flat beans:100:g,Green peas:0.5:cup,Brinjal:2:pieces,Besan:0.5:cup,Fenugreek leaves:1:cup,Coconut:0.5:cup,Green chillies:4:pieces,Ginger:1:pieces,Oil:4:tbsp,Sugar:1:tsp,Salt:1:tsp,Turmeric powder:0.5:tsp', steps:'Make muthiya dumplings from besan, fenugreek leaves and spices|Cut all vegetables into chunks|Layer vegetables in a heavy pot with spice paste|Add muthiya dumplings on top|Cook covered on low heat for 40 minutes until tender|Garnish with fresh coconut and coriander' },
  { slug:'dal-dhokli', name:'Dal Dhokli', hi:'दाल ढोकली', mr:'डाळ ढोकळी', c:'gujarati', v:true, m:['lunch','dinner'], cal:380, acc:null, d:'medium', p:20, ck:35, desc:'Wheat flour dumplings simmered in a sweet-sour toor dal — a Gujarati one-pot comfort meal.', ings:'Toor dal:1:cup,Wheat flour:1:cup,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Jaggery:1:tbsp,Tamarind pulp:1:tbsp,Peanuts:2:tbsp,Oil:2:tbsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Salt:1:tsp,Cinnamon stick:1:pieces,Cloves:3:pieces', steps:'Pressure cook toor dal until soft|Knead wheat flour with spices and oil into stiff dough|Roll thin and cut into diamond shapes|Add jaggery, tamarind, peanuts to dal and bring to boil|Drop dhokli pieces into simmering dal|Cook 10-12 minutes until dhokli are done|Temper with mustard, curry leaves and pour over' },
  { slug:'thepla', name:'Thepla', hi:'थेपला', mr:'थेपला', c:'gujarati', v:true, m:['breakfast','lunch','dinner'], cal:220, acc:null, d:'easy', p:15, ck:15, desc:'Spiced flatbread made with wheat flour and fenugreek leaves — the quintessential Gujarati travel food.', ings:'Wheat flour:2:cup,Fenugreek leaves:1:cup,Yogurt:3:tbsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Cumin seeds:1:tsp,Oil:3:tbsp,Salt:1:tsp,Sugar:0.5:tsp', steps:'Mix flour with chopped fenugreek leaves, spices, yogurt and oil|Knead into soft dough, rest 10 minutes|Roll into thin circles|Cook on tawa with oil on both sides until golden spots appear|Serve with pickle or yogurt' },
  { slug:'handvo', name:'Handvo', hi:'हांडवो', mr:'हांडवो', c:'gujarati', v:true, m:['breakfast','lunch'], cal:250, acc:null, d:'medium', p:480, ck:30, desc:'Savory baked cake made from a fermented batter of rice and lentils with vegetables.', ings:'Rice:1:cup,Chana dal:0.25:cup,Toor dal:0.25:cup,Urad dal:0.25:cup,Bottle gourd:1:cup,Yogurt:0.5:cup,Sesame seeds:1:tbsp,Mustard seeds:1:tsp,Oil:3:tbsp,Green chillies:3:pieces,Ginger:1:pieces,Salt:1:tsp,Turmeric powder:0.5:tsp', steps:'Soak rice and dals overnight, grind to thick batter|Add grated bottle gourd, yogurt and spices, ferment overnight|Heat oil in pan, add sesame and mustard seeds|Pour batter, cook covered on low heat 20 minutes|Flip and cook other side until golden and cooked through' },
  { slug:'khandvi', name:'Khandvi', hi:'खांडवी', mr:'खांडवी', c:'gujarati', v:true, m:['breakfast'], cal:160, acc:null, d:'hard', p:15, ck:15, desc:'Delicate rolled-up gram flour sheets tempered with mustard seeds and coconut — requires skill to get right.', ings:'Besan:1:cup,Yogurt:1:cup,Turmeric powder:0.25:tsp,Water:1:cup,Mustard seeds:1:tsp,Curry leaves:8:pieces,Coconut:2:tbsp,Oil:2:tbsp,Salt:0.5:tsp,Green chillies:2:pieces', steps:'Whisk besan, yogurt, turmeric, salt and water until smooth|Cook on medium heat stirring constantly until thick paste forms|Spread thin on greased surface immediately|Let cool slightly, cut into strips and roll up|Temper mustard seeds, curry leaves in oil|Pour over rolls, garnish with coconut' },
  { slug:'sev-tameta', name:'Sev Tameta Nu Shaak', hi:'सेव टमाटर', mr:'शेव टोमॅटो', c:'gujarati', v:true, m:['lunch','dinner'], cal:220, acc:'roti', d:'easy', p:10, ck:15, desc:'A quick Gujarati tomato curry topped with crispy sev — sweet, tangy, and crunchy.', ings:'Tomato:4:pieces,Sev:1:cup,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Sugar:1:tsp,Oil:2:tbsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Curry leaves:6:pieces,Coriander leaves:2:tbsp,Salt:1:tsp', steps:'Heat oil, temper mustard and cumin seeds|Add chopped tomatoes with turmeric, chilli powder|Cook until tomatoes break down into thick gravy|Add sugar and salt to balance|Top generously with crispy sev before serving' },
  { slug:'gujarati-kadhi', name:'Gujarati Kadhi', hi:'गुजराती कढ़ी', mr:'गुजराती कढी', c:'gujarati', v:true, m:['lunch','dinner'], cal:200, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'A sweet and sour yogurt-gram flour curry — thinner and sweeter than its Punjabi cousin.', ings:'Yogurt:1:cup,Besan:2:tbsp,Sugar:2:tsp,Green chillies:3:pieces,Ginger:1:pieces,Curry leaves:10:pieces,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Cinnamon stick:1:pieces,Cloves:2:pieces,Oil:2:tbsp,Salt:1:tsp,Water:3:cup', steps:'Whisk yogurt, besan and water until smooth|Add sugar, salt and bring to boil stirring continuously|Simmer on low heat for 15 minutes|Temper mustard, cumin, curry leaves, cinnamon, cloves in oil|Add whole green chillies and ginger|Pour tempering into kadhi, simmer 5 more minutes' },
  { slug:'khichdi-gujarati', name:'Gujarati Khichdi', hi:'गुजराती खिचड़ी', mr:'गुजराती खिचडी', c:'gujarati', v:true, m:['lunch','dinner'], cal:300, acc:null, d:'easy', p:10, ck:25, desc:'A comforting one-pot rice and mung dal porridge with ghee — pairs with kadhi and papad.', ings:'Rice:1:cup,Moong dal:0.5:cup,Turmeric powder:0.5:tsp,Ghee:2:tbsp,Cumin seeds:1:tsp,Salt:1:tsp,Water:4:cup,Green chillies:2:pieces,Ginger:1:pieces', steps:'Wash rice and dal together|Heat ghee, add cumin seeds, chillies, ginger|Add rice, dal and turmeric|Add water, salt and pressure cook 3 whistles|Mash lightly, add more ghee on top|Serve hot with kadhi and papad' },
  { slug:'patra', name:'Patra', hi:'पात्रा', mr:'पात्रा', c:'gujarati', v:true, m:['breakfast','lunch'], cal:190, acc:null, d:'hard', p:30, ck:25, desc:'Colocasia leaves spread with spiced gram flour paste, rolled, steamed, and sliced into pinwheels.', ings:'Colocasia leaves:8:pieces,Besan:1:cup,Tamarind pulp:2:tbsp,Jaggery:2:tbsp,Red chilli powder:1:tsp,Turmeric powder:0.5:tsp,Sesame seeds:2:tbsp,Oil:3:tbsp,Mustard seeds:1:tsp,Salt:1:tsp', steps:'Make paste of besan, tamarind, jaggery, spices and water|Spread paste on each colocasia leaf|Stack and roll tightly into a log|Steam for 20 minutes until firm|Slice into rounds|Temper mustard seeds, sesame in oil and pour over' },
  { slug:'dabeli', name:'Dabeli', hi:'दाबेली', mr:'दाबेली', c:'gujarati', v:true, m:['breakfast','lunch'], cal:320, acc:null, d:'easy', p:15, ck:10, desc:'Spiced mashed potato filling in a pav bun with chutneys, pomegranate, and sev — Kutchi street food.', ings:'Potato:3:pieces,Pav bread:4:pieces,Dabeli masala:2:tbsp,Tamarind chutney:2:tbsp,Garlic chutney:1:tbsp,Peanuts:2:tbsp,Pomegranate:0.25:cup,Sev:0.5:cup,Oil:2:tbsp,Salt:0.5:tsp', steps:'Boil and mash potatoes|Mix with dabeli masala, salt and little oil|Slit pav buns, apply chutneys inside|Stuff with potato mixture|Garnish with roasted peanuts, pomegranate and sev|Toast on tawa with butter until crispy' },
  { slug:'bataka-nu-shaak', name:'Bataka Nu Shaak', hi:'बटाका नू शाक', mr:'बटाट्याची भाजी', c:'gujarati', v:true, m:['lunch','dinner'], cal:240, acc:'roti', d:'easy', p:10, ck:20, desc:'Simple Gujarati potato curry with a sweet-spicy tomato gravy — everyday comfort food.', ings:'Potato:4:pieces,Tomato:2:pieces,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Coriander powder:1:tsp,Sugar:0.5:tsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Curry leaves:8:pieces,Oil:2:tbsp,Salt:1:tsp,Coriander leaves:2:tbsp', steps:'Cube potatoes|Heat oil, temper mustard, cumin, curry leaves|Add tomatoes, cook until soft|Add spices, sugar and salt|Add potatoes with water, cover and cook until tender|Garnish with coriander leaves' },
  { slug:'muthiya', name:'Muthiya', hi:'मुठिया', mr:'मुठिया', c:'gujarati', v:true, m:['breakfast'], cal:200, acc:null, d:'easy', p:15, ck:20, desc:'Steamed fenugreek and wheat flour dumplings, sliced and tempered — healthy Gujarati snack or breakfast.', ings:'Wheat flour:1:cup,Besan:0.5:cup,Fenugreek leaves:1:cup,Yogurt:3:tbsp,Turmeric powder:0.5:tsp,Sesame seeds:1:tbsp,Oil:3:tbsp,Mustard seeds:1:tsp,Salt:1:tsp,Sugar:0.5:tsp,Green chillies:2:pieces', steps:'Mix flours, chopped fenugreek, yogurt, spices into dough|Shape into cylindrical logs|Steam for 15 minutes|Cool and slice into rounds|Temper mustard seeds, sesame in oil|Toss sliced muthiya in tempering until lightly crisp' },
  { slug:'ringna-bataka', name:'Ringna Bataka Nu Shaak', hi:'बैंगन आलू', mr:'वांगी बटाटा', c:'gujarati', v:true, m:['lunch','dinner'], cal:260, acc:'roti', d:'easy', p:10, ck:25, desc:'Brinjal and potato curry in a peanut-sesame masala — a Gujarati home-cooking staple.', ings:'Brinjal:3:pieces,Potato:2:pieces,Peanuts:2:tbsp,Sesame seeds:1:tbsp,Turmeric powder:0.5:tsp,Red chilli powder:1:tsp,Coriander powder:1:tsp,Jaggery:1:tsp,Oil:3:tbsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Salt:1:tsp', steps:'Cut brinjal and potato into chunks|Roast and grind peanuts and sesame into coarse powder|Heat oil, temper mustard and curry leaves|Add vegetables with turmeric, cook covered|Add peanut-sesame powder, jaggery, other spices|Cook until vegetables are tender and masala coats them' },
  { slug:'mag-ni-dal', name:'Mag Ni Dal', hi:'मूंग की दाल', mr:'मुगाची डाळ', c:'gujarati', v:true, m:['lunch','dinner'], cal:220, acc:'steamed-rice', d:'easy', p:10, ck:25, desc:'Simple Gujarati moong dal with a sweet touch and ghee tadka — everyday lentil comfort.', ings:'Moong dal:1:cup,Turmeric powder:0.5:tsp,Jaggery:1:tsp,Ghee:2:tbsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Dried red chillies:2:pieces,Curry leaves:8:pieces,Salt:1:tsp,Green chillies:2:pieces,Ginger:1:pieces,Water:3:cup', steps:'Wash dal, cook with turmeric and water until soft|Mash lightly, add salt and jaggery|Temper mustard, cumin, chillies, curry leaves in ghee|Add ginger, pour over dal|Simmer 5 minutes and serve with rice' },
  { slug:'fafda-jalebi', name:'Fafda', hi:'फाफड़ा', mr:'फाफडा', c:'gujarati', v:true, m:['breakfast'], cal:350, acc:null, d:'medium', p:20, ck:20, desc:'Crispy gram flour strips, a Sunday morning ritual in Gujarat — served with green chutney and jalebi.', ings:'Besan:2:cup,Ajwain:1:tsp,Turmeric powder:0.25:tsp,Oil:4:tbsp,Salt:0.5:tsp,Baking soda:0.25:tsp,Water:0.5:cup', steps:'Mix besan, ajwain, turmeric, salt, baking soda|Add oil and knead with water into stiff dough|Rest 15 minutes|Roll into thin strips or press through mould|Deep fry in hot oil until crispy and golden|Drain and serve with green chutney' },
  { slug:'usal-gujarati', name:'Gujarati Usal', hi:'गुजराती उसल', mr:'गुजराती उसळ', c:'gujarati', v:true, m:['lunch','dinner'], cal:280, acc:'roti', d:'easy', p:480, ck:20, desc:'Sprouted moong bean curry with a light Gujarati spice profile — nutritious everyday sabzi.', ings:'Moong beans:1:cup,Tomato:2:pieces,Green chillies:2:pieces,Ginger:1:pieces,Turmeric powder:0.5:tsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Curry leaves:8:pieces,Oil:2:tbsp,Salt:1:tsp,Lemon juice:1:tbsp,Coriander leaves:2:tbsp', steps:'Soak moong overnight, drain and sprout for a day|Heat oil, temper mustard, cumin, curry leaves|Add ginger, chillies, tomatoes|Add sprouts with turmeric, salt and little water|Cook covered until sprouts are tender|Finish with lemon juice and coriander' },
  { slug:'lilva-kachori', name:'Lilva Kachori', hi:'लीलवा कचोरी', mr:'लिळवा कचोरी', c:'gujarati', v:true, m:['breakfast'], cal:300, acc:null, d:'medium', p:20, ck:20, desc:'Crispy fried pastry stuffed with fresh tuvar (pigeon pea) filling — a seasonal Gujarati treat.', ings:'Maida:2:cup,Fresh tuvar:1:cup,Green chillies:3:pieces,Ginger:1:pieces,Sugar:1:tsp,Sesame seeds:1:tsp,Oil:3:tbsp,Salt:0.5:tsp,Cumin seeds:1:tsp', steps:'Knead maida with oil and salt into firm dough|Mash tuvar with green chillies, ginger, sugar, sesame|Make small balls of dough, flatten|Place filling in center, seal and flatten slightly|Deep fry on medium heat until golden and crispy|Serve hot with green chutney' },
  { slug:'gujarati-dal', name:'Gujarati Dal', hi:'गुजराती दाल', mr:'गुजराती डाळ', c:'gujarati', v:true, m:['lunch','dinner'], cal:230, acc:'steamed-rice', d:'easy', p:10, ck:25, desc:'Sweet, sour, and spicy toor dal — the signature Gujarati lentil with its unique sweet-tangy balance.', ings:'Toor dal:1:cup,Tomato:1:pieces,Jaggery:2:tbsp,Tamarind pulp:1:tbsp,Peanuts:2:tbsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Curry leaves:8:pieces,Ghee:2:tbsp,Salt:1:tsp,Cinnamon stick:1:pieces,Cloves:2:pieces', steps:'Pressure cook toor dal with turmeric until soft|Add jaggery, tamarind, tomato, peanuts|Simmer until flavors meld|Temper mustard, cumin, curry leaves, cinnamon, cloves in ghee|Pour tempering into dal|Adjust sweet-sour balance and serve with rice' },
  { slug:'khakhra', name:'Khakhra', hi:'खाखरा', mr:'खाखरा', c:'gujarati', v:true, m:['breakfast'], cal:140, acc:null, d:'easy', p:10, ck:15, desc:'Thin crispy roasted flatbread made from whole wheat — light Gujarati breakfast or snack.', ings:'Wheat flour:1:cup,Oil:1:tbsp,Cumin seeds:0.5:tsp,Salt:0.5:tsp,Water:0.25:cup,Turmeric powder:0.25:tsp', steps:'Mix flour, cumin, turmeric, salt|Knead with water into stiff dough|Roll very thin circles|Roast on tawa pressing with cloth until crispy|Apply oil and press until fully crisp and golden|Cool — stays crispy for days' },

  // ===== BENGALI (18) =====
  { slug:'shukto', name:'Shukto', hi:'शुक्तो', mr:'शुक्तो', c:'bengali', v:true, m:['lunch','dinner'], cal:220, acc:'steamed-rice', d:'medium', p:15, ck:25, desc:'A mildly bitter mixed vegetable curry with poppy seed paste — always served as the first course in a Bengali meal.', ings:'Bitter gourd:1:pieces,Raw banana:1:pieces,Drumstick:2:pieces,Potato:1:pieces,Brinjal:1:pieces,Poppy seeds:2:tbsp,Milk:0.5:cup,Mustard seeds:1:tsp,Bay leaves:1:pieces,Ginger:1:pieces,Ghee:2:tbsp,Salt:1:tsp,Sugar:1:tsp,Turmeric powder:0.5:tsp', steps:'Cut all vegetables into batons|Fry bitter gourd until crispy, set aside|Grind poppy seeds into smooth paste|Sauté vegetables in ghee with mustard, bay leaf|Add turmeric, poppy paste and milk|Simmer until vegetables are tender|Add fried bitter gourd, sugar and serve' },
  { slug:'aloo-posto', name:'Aloo Posto', hi:'आलू पोस्तो', mr:'आलू पोस्तो', c:'bengali', v:true, m:['lunch','dinner'], cal:260, acc:'steamed-rice', d:'easy', p:15, ck:20, desc:'Potatoes cooked in a creamy ground poppy seed paste — a beloved Bengali comfort food.', ings:'Potato:4:pieces,Poppy seeds:3:tbsp,Green chillies:3:pieces,Mustard oil:3:tbsp,Turmeric powder:0.5:tsp,Salt:1:tsp,Sugar:0.5:tsp,Onion:1:pieces', steps:'Soak poppy seeds in water for 30 minutes, grind to paste|Cube potatoes, fry lightly in mustard oil|Add onion, turmeric, green chillies|Add poppy seed paste with water|Cover and cook until potatoes are tender|Finish with raw mustard oil drizzle' },
  { slug:'begun-bhaja', name:'Begun Bhaja', hi:'बैगुन भाजा', mr:'बैगुन भाजा', c:'bengali', v:true, m:['lunch','dinner'], cal:180, acc:'steamed-rice', d:'easy', p:5, ck:10, desc:'Thin brinjal slices marinated in turmeric and salt, shallow fried until crispy — Bengali everyday side.', ings:'Brinjal:2:pieces,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Mustard oil:4:tbsp,Salt:0.5:tsp', steps:'Slice brinjal into thin rounds|Marinate with turmeric, chilli powder and salt|Heat mustard oil in pan|Fry slices until golden and crispy on both sides|Drain on paper and serve with hot rice' },
  { slug:'ilish-bhapa', name:'Ilish Bhapa', hi:'इलिश भापा', mr:'इलिश भापा', c:'bengali', v:false, m:['lunch','dinner'], cal:380, acc:'steamed-rice', d:'medium', p:15, ck:25, desc:'Hilsa fish steamed in a mustard-coconut paste wrapped in banana leaf — the king of Bengali fish dishes.', ings:'Hilsa fish:500:g,Mustard seeds:3:tbsp,Coconut:0.5:cup,Green chillies:4:pieces,Turmeric powder:0.5:tsp,Mustard oil:3:tbsp,Salt:1:tsp', steps:'Grind mustard seeds, coconut, green chillies into fine paste|Marinate fish with paste, turmeric, salt and mustard oil|Wrap in banana leaf or foil|Steam for 20-25 minutes until fish is cooked|Serve in the leaf with mustard oil drizzle' },
  { slug:'chingri-malai-curry', name:'Chingri Malai Curry', hi:'चिंगरी मलाई करी', mr:'चिंगरी मलाई करी', c:'bengali', v:false, m:['lunch','dinner'], cal:350, acc:'steamed-rice', d:'medium', p:15, ck:25, desc:'Prawns in a luscious coconut milk gravy with whole spices — Bengali festive special.', ings:'Prawns:500:g,Coconut milk:1:cup,Onion:2:pieces,Ginger:1:pieces,Turmeric powder:0.5:tsp,Bay leaves:2:pieces,Cardamom:3:pieces,Cinnamon stick:1:pieces,Sugar:1:tsp,Ghee:2:tbsp,Salt:1:tsp,Green chillies:3:pieces', steps:'Clean and devein prawns, marinate with turmeric and salt|Lightly fry prawns in ghee, set aside|Sauté onion with bay leaf, cardamom, cinnamon|Add ginger paste, turmeric|Add coconut milk, bring to gentle simmer|Add prawns, sugar, green chillies|Cook 5 minutes — do not boil vigorously' },
  { slug:'kosha-mangsho', name:'Kosha Mangsho', hi:'कोशा मांस', mr:'कोशा मांस', c:'bengali', v:false, m:['lunch','dinner'], cal:450, acc:'roti', d:'hard', p:20, ck:60, desc:'Slow-cooked dry Bengali mutton curry with a dark, rich, deeply spiced onion gravy.', ings:'Mutton (bone-in):500:g,Onion:3:pieces,Yogurt:0.5:cup,Ginger:2:pieces,Garlic:6:pieces,Bay leaves:2:pieces,Cardamom:4:pieces,Cinnamon stick:1:pieces,Cloves:4:pieces,Red chilli powder:1:tsp,Turmeric powder:0.5:tsp,Mustard oil:4:tbsp,Sugar:1:tsp,Salt:1:tsp', steps:'Marinate mutton with yogurt, turmeric, salt for 30 minutes|Heat mustard oil, fry onions until deep brown|Add ginger-garlic paste, whole spices|Add marinated mutton, cook on high to sear|Add chilli powder, sugar|Cover and slow cook on low for 45-60 minutes|The gravy should be dark, thick and clinging to meat' },
  { slug:'luchi-alur-dom', name:'Luchi Alur Dom', hi:'लुची आलूर दम', mr:'लुची आलूर दम', c:'bengali', v:true, m:['breakfast','lunch'], cal:380, acc:null, d:'medium', p:20, ck:25, desc:'Puffed deep-fried white flour bread with a rich spiced potato curry — Bengali Sunday breakfast.', ings:'Maida:2:cup,Potato:4:pieces,Tomato:2:pieces,Ginger:1:pieces,Bay leaves:1:pieces,Cumin seeds:1:tsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Ghee:1:tbsp,Oil:3:tbsp,Sugar:1:tsp,Salt:1:tsp,Green chillies:2:pieces', steps:'Knead maida with salt and ghee into smooth dough|Boil and quarter potatoes|Make gravy with tomato, ginger, spices|Add potatoes to gravy, simmer until thick|Roll luchi dough into small circles|Deep fry until puffed and golden|Serve luchi with alur dom' },
  { slug:'macher-jhol', name:'Macher Jhol', hi:'माछेर झोल', mr:'माशाचे झोल', c:'bengali', v:false, m:['lunch','dinner'], cal:300, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Light Bengali fish curry with potatoes in a turmeric-cumin gravy — everyday comfort.', ings:'Rohu fish:400:g,Potato:2:pieces,Tomato:2:pieces,Turmeric powder:1:tsp,Cumin seeds:1:tsp,Green chillies:3:pieces,Mustard oil:3:tbsp,Salt:1:tsp,Sugar:0.5:tsp,Bay leaves:1:pieces', steps:'Marinate fish with turmeric and salt|Fry fish lightly in mustard oil, set aside|Fry potatoes until golden|Add cumin, bay leaf, tomatoes to same oil|Add turmeric, water and bring to boil|Add potatoes, cook 5 minutes|Add fish, green chillies, simmer 5 minutes' },
  { slug:'chholar-dal', name:'Chholar Dal', hi:'छोलार दाल', mr:'छोलार डाळ', c:'bengali', v:true, m:['lunch','dinner'], cal:280, acc:'roti', d:'easy', p:10, ck:30, desc:'Bengali chana dal with coconut and raisins — subtly sweet, served with luchi on special occasions.', ings:'Chana dal:1:cup,Coconut:0.5:cup,Raisins:2:tbsp,Bay leaves:1:pieces,Ghee:2:tbsp,Cumin seeds:1:tsp,Turmeric powder:0.5:tsp,Ginger:1:pieces,Green chillies:2:pieces,Sugar:1:tsp,Salt:1:tsp', steps:'Soak and pressure cook chana dal with turmeric|Heat ghee, add cumin, bay leaf, ginger|Add coconut pieces, raisins|Add cooked dal with sugar, salt|Simmer until flavors meld|Finish with slit green chillies and ghee' },
  { slug:'doi-maach', name:'Doi Maach', hi:'दोई माछ', mr:'दोई मासा', c:'bengali', v:false, m:['lunch','dinner'], cal:320, acc:'steamed-rice', d:'medium', p:15, ck:25, desc:'Fish in a creamy yogurt gravy with mild spices — a celebratory Bengali preparation.', ings:'Rohu fish:500:g,Yogurt:1:cup,Onion:2:pieces,Ginger:1:pieces,Turmeric powder:0.5:tsp,Cumin powder:1:tsp,Cardamom:3:pieces,Cinnamon stick:1:pieces,Bay leaves:1:pieces,Sugar:1:tsp,Ghee:2:tbsp,Mustard oil:2:tbsp,Salt:1:tsp', steps:'Marinate fish with turmeric and salt, lightly fry|Whisk yogurt until smooth|Sauté onion in ghee with whole spices|Add ginger paste, cumin powder|Add whisked yogurt on low heat, stir|Add fried fish pieces, sugar|Simmer gently for 10 minutes without boiling' },
  { slug:'mochar-ghonto', name:'Mochar Ghonto', hi:'मोचार घोंटो', mr:'मोचार घोंटो', c:'bengali', v:true, m:['lunch','dinner'], cal:240, acc:'steamed-rice', d:'hard', p:30, ck:25, desc:'Banana flower cooked into a thick dry preparation with coconut and spices — unique Bengali delicacy.', ings:'Banana flower:1:pieces,Potato:1:pieces,Coconut:0.5:cup,Ghee:2:tbsp,Bay leaves:1:pieces,Cumin seeds:1:tsp,Turmeric powder:0.5:tsp,Ginger:1:pieces,Green chillies:2:pieces,Sugar:0.5:tsp,Salt:1:tsp', steps:'Clean banana flower, chop finely and soak in water|Boil or pressure cook until soft|Heat ghee, add cumin, bay leaf|Add grated coconut, fry lightly|Add chopped banana flower, potato, turmeric|Cook covered until dry and well combined|Finish with ghee and ginger' },
  { slug:'mishti-pulao', name:'Mishti Pulao', hi:'मिष्टी पुलाव', mr:'मिष्टी पुलाव', c:'bengali', v:true, m:['lunch','dinner'], cal:350, acc:null, d:'medium', p:15, ck:25, desc:'Sweet Bengali pulao with ghee, raisins, cashews, and warm spices — served at weddings and feasts.', ings:'Basmati rice:2:cup,Ghee:3:tbsp,Sugar:3:tbsp,Raisins:2:tbsp,Cashew nuts:10:pieces,Bay leaves:2:pieces,Cardamom:4:pieces,Cinnamon stick:1:pieces,Cloves:4:pieces,Saffron:0.25:tsp,Milk:2:tbsp,Salt:0.5:tsp', steps:'Soak rice for 30 minutes|Heat ghee, fry cashews and raisins, set aside|Add whole spices to ghee, then drained rice|Dissolve sugar in hot water, add saffron soaked in milk|Pour sugar water over rice|Cook covered on low heat until done|Garnish with fried cashews and raisins' },
  { slug:'dhokar-dalna', name:'Dhokar Dalna', hi:'ढोकार डालना', mr:'ढोकार डालना', c:'bengali', v:true, m:['lunch','dinner'], cal:280, acc:'steamed-rice', d:'medium', p:20, ck:25, desc:'Fried chana dal cakes in a spiced tomato gravy — a vegetarian Bengali classic that mimics fish curry.', ings:'Chana dal:1:cup,Tomato:2:pieces,Ginger:1:pieces,Cumin seeds:1:tsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Bay leaves:1:pieces,Sugar:1:tsp,Oil:4:tbsp,Salt:1:tsp,Green chillies:2:pieces', steps:'Soak and grind chana dal into thick paste|Cook paste with turmeric and salt until thick|Spread on greased plate, cool and cut into diamonds|Shallow fry pieces until golden on both sides|Make tomato gravy with cumin, ginger, spices|Add fried dhokas to gravy|Simmer 5 minutes until gravy coats them' },
  { slug:'egg-devil-bengali', name:'Dimer Devil', hi:'डिमेर डेविल', mr:'डिमेर डेविल', c:'bengali', v:false, m:['lunch','dinner'], cal:280, acc:'steamed-rice', d:'easy', p:10, ck:15, desc:'Hard-boiled eggs coated in spiced mince and deep fried — Bengal\'s answer to Scotch eggs.', ings:'Eggs:4:pieces,Chicken mince:200:g,Onion:1:pieces,Ginger:1:pieces,Green chillies:2:pieces,Besan:2:tbsp,Red chilli powder:0.5:tsp,Garam masala:0.5:tsp,Oil:3:tbsp,Salt:0.5:tsp,Bread crumbs:0.5:cup', steps:'Hard boil eggs, peel|Mix mince with chopped onion, ginger, chillies, spices|Coat each egg with mince mixture|Roll in besan then bread crumbs|Deep fry until golden brown|Cut in half and serve with kasundi mustard' },
  { slug:'cholar-dal-narkel', name:'Narkel Diye Cholar Dal', hi:'नारकेल छोलार दाल', mr:'नारळ छोलार डाळ', c:'bengali', v:true, m:['lunch','dinner'], cal:290, acc:'roti', d:'easy', p:10, ck:30, desc:'Bengali chana dal cooked with fresh coconut pieces — a simpler version of the festive chholar dal.', ings:'Chana dal:1:cup,Coconut:0.5:cup,Turmeric powder:0.5:tsp,Ghee:2:tbsp,Cumin seeds:1:tsp,Bay leaves:1:pieces,Dried red chillies:2:pieces,Ginger:1:pieces,Sugar:1:tsp,Salt:1:tsp', steps:'Soak and pressure cook chana dal with turmeric|Cut coconut into small pieces|Heat ghee, add cumin, bay leaf, dried chillies|Add coconut pieces, fry until edges brown|Add cooked dal, sugar, salt|Simmer 10 minutes until thick' },
  { slug:'bhetki-paturi', name:'Bhetki Paturi', hi:'भेटकी पातुरी', mr:'भेटकी पातुरी', c:'bengali', v:false, m:['lunch','dinner'], cal:280, acc:'steamed-rice', d:'medium', p:15, ck:20, desc:'Bhetki fish marinated in mustard paste and steamed in banana leaf — delicate and aromatic.', ings:'Bhetki fish:400:g,Mustard seeds:3:tbsp,Coconut:3:tbsp,Green chillies:3:pieces,Turmeric powder:0.5:tsp,Mustard oil:2:tbsp,Salt:1:tsp', steps:'Grind mustard seeds, coconut, green chillies into paste|Marinate fish with paste, turmeric, salt, mustard oil|Wrap each piece in banana leaf|Tie with string to secure|Steam or grill for 15-20 minutes|Serve in the banana leaf' },
  { slug:'lau-ghonto', name:'Lau Ghonto', hi:'लाउ घोंटो', mr:'लाउ घोंटो', c:'bengali', v:true, m:['lunch','dinner'], cal:180, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Bottle gourd mashed and cooked with milk and spices — a simple, comforting Bengali preparation.', ings:'Bottle gourd:500:g,Milk:0.5:cup,Ghee:2:tbsp,Bay leaves:1:pieces,Cumin seeds:1:tsp,Ginger:1:pieces,Turmeric powder:0.5:tsp,Sugar:1:tsp,Salt:1:tsp,Green chillies:2:pieces', steps:'Peel and grate bottle gourd|Heat ghee, add cumin, bay leaf|Add grated gourd with turmeric|Cook covered until soft|Mash lightly, add milk|Simmer until thick|Add sugar, green chillies and finish with ghee' },
  { slug:'posto-bora', name:'Posto Bora', hi:'पोस्तो बड़ा', mr:'पोस्तो बडा', c:'bengali', v:true, m:['lunch','dinner'], cal:160, acc:'steamed-rice', d:'easy', p:15, ck:10, desc:'Poppy seed fritters — crispy fried patties of ground poppy seeds with onion and green chillies.', ings:'Poppy seeds:0.5:cup,Onion:1:pieces,Green chillies:3:pieces,Salt:0.5:tsp,Mustard oil:3:tbsp,Rice flour:1:tbsp', steps:'Soak poppy seeds for 2 hours|Grind into thick paste|Mix with chopped onion, green chillies, salt, rice flour|Shape into small flat patties|Shallow fry in mustard oil until golden on both sides|Serve as side dish with rice' },

  // ===== KERALA (18) =====
  { slug:'appam-stew', name:'Appam with Stew', hi:'अप्पम स्टू', mr:'अप्पम स्ट्यू', c:'kerala', v:false, m:['breakfast','dinner'], cal:380, acc:null, d:'medium', p:480, ck:25, desc:'Lacy fermented rice hoppers served with a creamy coconut-vegetable or chicken stew — classic Kerala breakfast.', ings:'Raw rice:2:cup,Coconut:1:cup,Yeast:0.5:tsp,Sugar:1:tsp,Chicken (bone-in):400:g,Potato:2:pieces,Coconut milk:2:cup,Onion:2:pieces,Green chillies:4:pieces,Ginger:1:pieces,Cardamom:3:pieces,Cinnamon stick:1:pieces,Cloves:3:pieces,Curry leaves:8:pieces,Salt:1:tsp', steps:'Soak rice overnight, grind with coconut into batter|Add yeast, sugar, ferment overnight|For stew: cook chicken with whole spices|Add potatoes, thin coconut milk first|When cooked, add thick coconut milk|Pour appam batter in appam maker, swirl|Cover and cook until edges crisp and center is soft' },
  { slug:'puttu-kadala', name:'Puttu with Kadala Curry', hi:'पुट्टू कडला करी', mr:'पुट्टू कडला करी', c:'kerala', v:true, m:['breakfast'], cal:350, acc:null, d:'easy', p:480, ck:20, desc:'Steamed rice flour and coconut cylinders served with a spicy black chickpea curry — Kerala staple breakfast.', ings:'Rice flour:2:cup,Coconut:1:cup,Black chickpeas:1:cup,Onion:2:pieces,Tomato:1:pieces,Coconut milk:0.5:cup,Red chilli powder:1:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Garam masala:0.5:tsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Coconut oil:2:tbsp,Salt:1:tsp', steps:'Soak black chickpeas overnight, pressure cook|Sprinkle water on rice flour, make it crumbly|Layer rice flour and coconut in puttu maker, steam|For kadala: sauté onion, add tomato and spices|Add cooked chickpeas with water|Add coconut milk, simmer|Serve puttu broken up with kadala curry poured over' },
  { slug:'kerala-fish-curry', name:'Kerala Fish Curry', hi:'केरला फिश करी', mr:'केरळा फिश करी', c:'kerala', v:false, m:['lunch','dinner'], cal:330, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Fish simmered in a tangy red chilli and kokum gravy with coconut — called meen curry, gets better overnight.', ings:'Fish (pomfret/kingfish):500:g,Kokum:4:pieces,Coconut oil:3:tbsp,Onion:2:pieces,Tomato:1:pieces,Red chilli powder:2:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Fenugreek seeds:0.25:tsp,Mustard seeds:1:tsp,Curry leaves:10:pieces,Salt:1:tsp', steps:'Heat coconut oil, add fenugreek and mustard seeds|Add onion, curry leaves, cook until soft|Add tomato, chilli, turmeric, coriander|Add water and kokum, bring to boil|Slide fish pieces into simmering gravy|Cook 8-10 minutes without stirring|Let rest — flavor improves overnight' },
  { slug:'avial-kerala', name:'Avial', hi:'अवियल', mr:'अवियल', c:'kerala', v:true, m:['lunch','dinner'], cal:250, acc:'steamed-rice', d:'medium', p:20, ck:20, desc:'Mixed vegetables in a thick coconut-yogurt sauce with curry leaves — a Kerala Onam feast essential.', ings:'Drumstick:2:pieces,Raw banana:1:pieces,Yam:100:g,Beans:100:g,Carrot:1:pieces,Ash gourd:100:g,Coconut:1:cup,Yogurt:0.5:cup,Green chillies:4:pieces,Curry leaves:10:pieces,Coconut oil:2:tbsp,Turmeric powder:0.5:tsp,Salt:1:tsp', steps:'Cut all vegetables into long batons|Cook vegetables with turmeric and salt until tender|Grind coconut with green chillies into coarse paste|Add coconut paste to vegetables|Add yogurt, mix gently|Add curry leaves and raw coconut oil|Do not boil after adding yogurt' },
  { slug:'thoran', name:'Cabbage Thoran', hi:'थोरन', mr:'थोरन', c:'kerala', v:true, m:['lunch','dinner'], cal:150, acc:'steamed-rice', d:'easy', p:10, ck:10, desc:'Finely chopped cabbage stir-fried with coconut and mustard seeds — a quick Kerala dry side dish.', ings:'Cabbage:300:g,Coconut:0.5:cup,Mustard seeds:1:tsp,Urad dal:1:tsp,Dried red chillies:2:pieces,Curry leaves:8:pieces,Turmeric powder:0.25:tsp,Coconut oil:2:tbsp,Onion:1:pieces,Salt:0.5:tsp', steps:'Finely chop cabbage and onion|Heat coconut oil, add mustard seeds, urad dal, chillies|Add curry leaves and onion|Add cabbage with turmeric and salt|Cook covered on medium heat until just tender|Add grated coconut, toss and serve' },
  { slug:'olan', name:'Olan', hi:'ओलन', mr:'ओलन', c:'kerala', v:true, m:['lunch','dinner'], cal:200, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Ash gourd and black-eyed peas in thin coconut milk — one of the mildest and most soothing Kerala curries.', ings:'Ash gourd:300:g,Black-eyed peas:0.5:cup,Coconut milk:1.5:cup,Green chillies:3:pieces,Curry leaves:8:pieces,Coconut oil:1:tbsp,Salt:1:tsp', steps:'Soak and cook black-eyed peas until tender|Cube ash gourd|Cook gourd in thin coconut milk with green chillies|Add cooked peas|When gourd is tender, add thick coconut milk|Add curry leaves and coconut oil|Do not boil — just heat through' },
  { slug:'erissery', name:'Erissery', hi:'एरिसेरी', mr:'एरिसेरी', c:'kerala', v:true, m:['lunch','dinner'], cal:280, acc:'steamed-rice', d:'medium', p:15, ck:25, desc:'Pumpkin and red beans in a coarse coconut paste — a rich, earthy Onam sadya staple.', ings:'Pumpkin:300:g,Red beans:0.5:cup,Coconut:1:cup,Cumin seeds:1:tsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Curry leaves:8:pieces,Coconut oil:2:tbsp,Mustard seeds:1:tsp,Salt:1:tsp', steps:'Soak and cook red beans|Cube pumpkin, cook with turmeric and salt|Grind coconut with cumin into coarse paste|Mash pumpkin lightly|Add coconut paste and cooked beans|Simmer until thick|Temper mustard seeds, curry leaves in coconut oil' },
  { slug:'karimeen-pollichathu', name:'Karimeen Pollichathu', hi:'करीमीन पोल्लीचत्तू', mr:'करीमीन पोल्लीचत्तू', c:'kerala', v:false, m:['lunch','dinner'], cal:350, acc:'steamed-rice', d:'medium', p:15, ck:20, desc:'Pearl spot fish marinated in spices, pan-fried, then wrapped in banana leaf with masala — Kerala backwater specialty.', ings:'Pearl spot fish:500:g,Onion:2:pieces,Tomato:1:pieces,Coconut oil:3:tbsp,Red chilli powder:1:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Garam masala:0.5:tsp,Curry leaves:10:pieces,Ginger:1:pieces,Garlic:4:pieces,Salt:1:tsp,Lemon juice:1:tbsp', steps:'Marinate fish with turmeric, chilli, salt and lemon juice|Shallow fry fish until golden|Sauté onion, ginger-garlic, tomato with spices|Place fish on banana leaf, top with masala|Fold leaf over, secure with toothpick|Pan-grill wrapped fish for 5 minutes each side' },
  { slug:'idiyappam', name:'Idiyappam', hi:'इडियप्पम', mr:'इडियप्पम', c:'kerala', v:true, m:['breakfast','dinner'], cal:180, acc:null, d:'medium', p:15, ck:10, desc:'Delicate steamed rice noodle nests — served with coconut milk, egg curry, or vegetable stew for breakfast.', ings:'Rice flour:2:cup,Water:2:cup,Salt:0.5:tsp,Coconut oil:1:tbsp', steps:'Boil water with salt and oil|Add rice flour, mix quickly into dough|Knead until smooth|Press through idiyappam maker onto steamer plates in circular nests|Steam for 5-7 minutes|Serve with coconut milk or stew' },
  { slug:'kerala-chicken-stew', name:'Kerala Chicken Stew', hi:'केरला चिकन स्टू', mr:'केरळा चिकन स्ट्यू', c:'kerala', v:false, m:['breakfast','dinner'], cal:340, acc:null, d:'easy', p:15, ck:30, desc:'Mildly spiced chicken and vegetables in coconut milk — the classic pair for appam and idiyappam.', ings:'Chicken (bone-in):500:g,Potato:2:pieces,Carrot:1:pieces,Beans:100:g,Onion:2:pieces,Coconut milk:2:cup,Green chillies:4:pieces,Ginger:1:pieces,Cardamom:3:pieces,Cinnamon stick:1:pieces,Cloves:3:pieces,Curry leaves:8:pieces,Coconut oil:2:tbsp,Salt:1:tsp', steps:'Cook chicken pieces with thin coconut milk and whole spices|Add cubed potatoes, carrots, beans|Cook until vegetables and chicken are tender|Add sliced onion, green chillies, ginger|Pour in thick coconut milk|Heat gently — never boil|Add curry leaves and coconut oil' },
  { slug:'fish-moilee', name:'Fish Moilee', hi:'फिश मोइली', mr:'फिश मोइली', c:'kerala', v:false, m:['lunch','dinner'], cal:310, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Fish in a mild yellow coconut milk gravy with green chillies — lighter than the red fish curry.', ings:'Fish (pomfret/kingfish):500:g,Coconut milk:1.5:cup,Onion:2:pieces,Tomato:1:pieces,Green chillies:4:pieces,Ginger:1:pieces,Turmeric powder:0.5:tsp,Mustard seeds:0.5:tsp,Curry leaves:8:pieces,Coconut oil:2:tbsp,Salt:1:tsp', steps:'Marinate fish with turmeric and salt|Heat coconut oil, add mustard seeds, curry leaves|Add sliced onion, ginger, green chillies|Add tomato, cook until soft|Add thin coconut milk, bring to simmer|Add fish, cook 8 minutes|Add thick coconut milk, heat gently and serve' },
  { slug:'beetroot-thoran', name:'Beetroot Thoran', hi:'बीटरूट थोरन', mr:'बीटरूट थोरन', c:'kerala', v:true, m:['lunch','dinner'], cal:140, acc:'steamed-rice', d:'easy', p:10, ck:10, desc:'Grated beetroot stir-fried with coconut and spices — colorful Kerala dry side dish.', ings:'Beetroot:2:pieces,Coconut:0.5:cup,Mustard seeds:1:tsp,Urad dal:1:tsp,Dried red chillies:2:pieces,Curry leaves:8:pieces,Turmeric powder:0.25:tsp,Coconut oil:2:tbsp,Onion:1:pieces,Salt:0.5:tsp', steps:'Grate beetroot|Heat coconut oil, temper mustard, urad dal, chillies|Add onion and curry leaves|Add grated beetroot with turmeric and salt|Cook covered until tender|Add grated coconut, toss well' },
  { slug:'prawn-curry-kerala', name:'Kerala Prawn Curry', hi:'केरला प्रॉन करी', mr:'केरळा कोळंबी करी', c:'kerala', v:false, m:['lunch','dinner'], cal:300, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Prawns in a red coconut gravy with kokum — tangy, spicy, and quintessentially coastal Kerala.', ings:'Prawns:400:g,Coconut:1:cup,Onion:2:pieces,Kokum:3:pieces,Red chilli powder:1.5:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Fenugreek seeds:0.25:tsp,Mustard seeds:1:tsp,Curry leaves:10:pieces,Coconut oil:2:tbsp,Salt:1:tsp', steps:'Grind coconut into paste|Heat oil, add fenugreek, mustard, curry leaves|Add onion, cook until soft|Add chilli, turmeric, coriander powders|Add coconut paste with water|Add kokum, bring to simmer|Add cleaned prawns, cook 5-7 minutes' },
  { slug:'egg-roast-kerala', name:'Kerala Egg Roast', hi:'केरला एग रोस्ट', mr:'केरळा एग रोस्ट', c:'kerala', v:false, m:['lunch','dinner'], cal:280, acc:'roti', d:'easy', p:10, ck:20, desc:'Hard-boiled eggs in a dark, thick onion-tomato masala — Kerala\'s favourite egg preparation, pairs with porotta.', ings:'Eggs:6:pieces,Onion:3:pieces,Tomato:2:pieces,Red chilli powder:1.5:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Garam masala:0.5:tsp,Ginger:1:pieces,Garlic:4:pieces,Curry leaves:10:pieces,Coconut oil:3:tbsp,Salt:1:tsp', steps:'Hard boil eggs, peel and slit|Fry eggs lightly in oil, set aside|Sauté sliced onions until dark brown|Add ginger-garlic, tomatoes|Add all spice powders, cook until oil separates|Add eggs, toss in masala|Garnish with curry leaves' },
  { slug:'vendakka-curry', name:'Vendakka Curry', hi:'भिंडी करी', mr:'भेंडी करी', c:'kerala', v:true, m:['lunch','dinner'], cal:180, acc:'steamed-rice', d:'easy', p:10, ck:15, desc:'Okra in a coconut-yogurt gravy — tangy Kerala-style bhindi that goes perfectly with rice.', ings:'Okra:300:g,Coconut:0.5:cup,Yogurt:0.5:cup,Onion:1:pieces,Green chillies:3:pieces,Turmeric powder:0.5:tsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Coconut oil:2:tbsp,Salt:0.5:tsp', steps:'Slit okra, fry in oil until crisp|Grind coconut with green chillies into paste|Sauté onion with mustard seeds and curry leaves|Add coconut paste, turmeric, salt with water|Add fried okra|Add yogurt, mix gently|Do not boil after adding yogurt' },
  { slug:'pachadi-kerala', name:'Pineapple Pachadi', hi:'अनानास पचड़ी', mr:'अननस पचडी', c:'kerala', v:true, m:['lunch','dinner'], cal:160, acc:'steamed-rice', d:'easy', p:10, ck:15, desc:'Sweet pineapple in a coconut-yogurt sauce tempered with mustard — a sadya essential.', ings:'Pineapple:1:cup,Coconut:0.5:cup,Yogurt:0.5:cup,Green chillies:2:pieces,Mustard seeds:1:tsp,Coconut oil:1:tbsp,Curry leaves:6:pieces,Sugar:2:tsp,Salt:0.5:tsp', steps:'Cook pineapple with chilli powder, salt and sugar until soft|Grind coconut with green chillies|Add coconut paste to pineapple|Add yogurt off heat|Temper mustard seeds, curry leaves in coconut oil|Pour over pachadi' },

  // ===== ANDHRA (15) =====
  { slug:'pesarattu', name:'Pesarattu', hi:'पेसारट्टू', mr:'पेसारट्टू', c:'andhra', v:true, m:['breakfast'], cal:220, acc:null, d:'easy', p:480, ck:10, desc:'Green moong dal dosa — a protein-rich Andhra breakfast crepe served with ginger chutney.', ings:'Moong beans:1:cup,Rice:0.25:cup,Green chillies:3:pieces,Ginger:1:pieces,Cumin seeds:1:tsp,Salt:1:tsp,Oil:2:tbsp', steps:'Soak moong and rice for 4 hours|Grind with ginger, chillies, cumin into batter|Add salt — no fermentation needed|Pour on hot tawa, spread thin|Drizzle oil, cook until crispy|Fold and serve with ginger chutney' },
  { slug:'hyderabadi-biryani', name:'Hyderabadi Dum Biryani', hi:'हैदराबादी दम बिरयानी', mr:'हैदराबादी दम बिर्याणी', c:'andhra', v:false, m:['lunch','dinner'], cal:520, acc:null, d:'hard', p:30, ck:45, desc:'Layered rice and meat slow-cooked in a sealed pot — the crown jewel of Hyderabadi cuisine.', ings:'Basmati rice:2:cup,Mutton (bone-in):500:g,Yogurt:1:cup,Onion:3:pieces,Ginger:2:pieces,Garlic:8:pieces,Green chillies:4:pieces,Mint leaves:0.5:cup,Coriander leaves:0.5:cup,Saffron:0.5:tsp,Milk:0.25:cup,Ghee:4:tbsp,Oil:3:tbsp,Salt:1:tsp,Biryani masala:2:tbsp', steps:'Marinate mutton in yogurt, ginger-garlic, biryani masala|Fry sliced onions until golden brown|Par-cook rice to 70% done|Layer: mutton, rice, fried onions, herbs, saffron milk|Seal pot with dough|Cook on high heat 5 min then low heat 35 min|Rest 10 minutes before opening|Gently mix layers while serving' },
  { slug:'gongura-pachadi', name:'Gongura Pachadi', hi:'गोंगूरा पचड़ी', mr:'गोंगूरा पचडी', c:'andhra', v:true, m:['lunch','dinner'], cal:120, acc:'steamed-rice', d:'easy', p:10, ck:15, desc:'Tangy sorrel leaf chutney — the most iconic Andhra condiment, fiery and sour.', ings:'Sorrel leaves:2:cup,Dried red chillies:6:pieces,Garlic:6:pieces,Mustard seeds:1:tsp,Fenugreek seeds:0.25:tsp,Urad dal:1:tsp,Oil:3:tbsp,Salt:1:tsp', steps:'Wash sorrel leaves|Heat oil, fry dried chillies and garlic|Add sorrel leaves, cook until wilted|Cool and grind into coarse paste|Temper mustard, fenugreek, urad dal in oil|Mix tempering into chutney' },
  { slug:'gutti-vankaya', name:'Gutti Vankaya Curry', hi:'गुट्टी वांकाया', mr:'गुट्टी वांगी', c:'andhra', v:true, m:['lunch','dinner'], cal:280, acc:'steamed-rice', d:'medium', p:20, ck:25, desc:'Stuffed baby brinjals in a spicy peanut-sesame-coconut gravy — a signature Andhra dish.', ings:'Baby brinjals:8:pieces,Peanuts:3:tbsp,Sesame seeds:2:tbsp,Coconut:3:tbsp,Onion:2:pieces,Tamarind pulp:1:tbsp,Red chilli powder:2:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Cumin seeds:1:tsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Oil:4:tbsp,Salt:1:tsp', steps:'Roast peanuts, sesame, coconut — grind into coarse masala|Slit brinjals into quarters keeping stem intact|Stuff masala into brinjals|Heat oil, add mustard, cumin, curry leaves|Add onion, cook until soft|Place stuffed brinjals, add remaining masala with tamarind water|Cook covered on low until brinjals are tender' },
  { slug:'chicken-65', name:'Chicken 65', hi:'चिकन 65', mr:'चिकन 65', c:'andhra', v:false, m:['dinner'], cal:380, acc:null, d:'medium', p:30, ck:15, desc:'Fiery deep-fried chicken bites with curry leaves and chillies — legendary Hyderabadi bar snack.', ings:'Chicken (boneless):500:g,Yogurt:3:tbsp,Red chilli powder:2:tsp,Ginger:1:pieces,Garlic:4:pieces,Cornstarch:2:tbsp,Eggs:1:pieces,Curry leaves:15:pieces,Green chillies:6:pieces,Lemon juice:1:tbsp,Oil:4:tbsp,Salt:1:tsp,Food colour red:0.25:tsp', steps:'Cut chicken into bite-sized pieces|Marinate with yogurt, chilli, ginger-garlic, cornstarch, egg, salt|Rest 30 minutes in fridge|Deep fry in batches until crispy and cooked through|In separate pan, fry curry leaves and green chillies|Toss fried chicken with the tempering|Squeeze lemon juice over and serve hot' },
  { slug:'tomato-pappu', name:'Tomato Pappu', hi:'टमाटर पप्पू', mr:'टोमॅटो पप्पू', c:'andhra', v:true, m:['lunch','dinner'], cal:220, acc:'steamed-rice', d:'easy', p:10, ck:25, desc:'Toor dal cooked with tomatoes and a classic Andhra tadka — everyday comfort lentils.', ings:'Toor dal:1:cup,Tomato:3:pieces,Turmeric powder:0.5:tsp,Red chilli powder:1:tsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Dried red chillies:2:pieces,Curry leaves:8:pieces,Garlic:3:pieces,Onion:1:pieces,Ghee:2:tbsp,Salt:1:tsp', steps:'Pressure cook dal with tomatoes and turmeric|Mash well|Temper mustard, cumin, dried chillies, garlic, curry leaves in ghee|Add onion, fry until golden|Pour tempering into dal|Add chilli powder, salt|Simmer 5 minutes and serve with rice' },
  { slug:'mirchi-ka-salan', name:'Mirchi Ka Salan', hi:'मिर्ची का सालन', mr:'मिरचीचे सालन', c:'andhra', v:true, m:['lunch','dinner'], cal:240, acc:'steamed-rice', d:'medium', p:15, ck:20, desc:'Long green chillies in a tangy peanut-sesame-tamarind gravy — the essential biryani accompaniment.', ings:'Long green chillies:8:pieces,Peanuts:3:tbsp,Sesame seeds:2:tbsp,Coconut:2:tbsp,Onion:2:pieces,Tamarind pulp:2:tbsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Oil:3:tbsp,Salt:1:tsp', steps:'Slit and lightly fry green chillies, set aside|Roast peanuts, sesame, coconut — grind to paste|Fry onion until golden|Add ground paste, turmeric, chilli powder|Add tamarind water, bring to simmer|Add fried chillies|Cook until gravy thickens and coats chillies' },
  { slug:'natu-kodi', name:'Natu Kodi Pulusu', hi:'नाटू कोड़ी पुलुसू', mr:'नाटू कोडी पुलुसू', c:'andhra', v:false, m:['lunch','dinner'], cal:380, acc:'steamed-rice', d:'medium', p:15, ck:40, desc:'Country chicken in a spicy tamarind-onion gravy — rustic Andhra flavors at their best.', ings:'Chicken (bone-in):500:g,Onion:3:pieces,Tomato:2:pieces,Tamarind pulp:2:tbsp,Red chilli powder:2:tsp,Turmeric powder:0.5:tsp,Coriander powder:1:tsp,Ginger:1:pieces,Garlic:6:pieces,Curry leaves:10:pieces,Mustard seeds:1:tsp,Oil:3:tbsp,Salt:1:tsp', steps:'Heat oil, add mustard seeds and curry leaves|Add onion, cook until brown|Add ginger-garlic, tomato|Add all spice powders, cook until oil separates|Add chicken pieces, sear on high heat|Add tamarind water, cover and cook 30 minutes|Gravy should be thick and clinging to chicken' },
  { slug:'dondakaya-fry', name:'Dondakaya Fry', hi:'टिंडा फ्राई', mr:'तोंडली फ्राय', c:'andhra', v:true, m:['lunch','dinner'], cal:150, acc:'steamed-rice', d:'easy', p:10, ck:15, desc:'Ivy gourd stir-fried with spices until crispy — a quick Andhra everyday vegetable.', ings:'Ivy gourd:300:g,Onion:1:pieces,Red chilli powder:1:tsp,Turmeric powder:0.25:tsp,Cumin seeds:1:tsp,Mustard seeds:1:tsp,Curry leaves:6:pieces,Oil:3:tbsp,Salt:0.5:tsp', steps:'Slice ivy gourd into thin rounds|Heat oil, add mustard, cumin, curry leaves|Add onion, sauté|Add sliced ivy gourd with turmeric, chilli, salt|Cook uncovered on medium heat stirring occasionally|Continue until crispy and browned' },
  { slug:'bagara-baingan', name:'Bagara Baingan', hi:'बगारा बैंगन', mr:'बगारा वांगी', c:'andhra', v:true, m:['lunch','dinner'], cal:270, acc:'steamed-rice', d:'medium', p:15, ck:25, desc:'Hyderabadi stuffed brinjal curry in a rich peanut-sesame-coconut gravy — a Deccan classic.', ings:'Baby brinjals:8:pieces,Peanuts:3:tbsp,Sesame seeds:2:tbsp,Coconut:3:tbsp,Onion:2:pieces,Tamarind pulp:1:tbsp,Red chilli powder:1.5:tsp,Turmeric powder:0.5:tsp,Curry leaves:10:pieces,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Oil:4:tbsp,Salt:1:tsp', steps:'Roast and grind peanuts, sesame, coconut into paste|Slit baby brinjals, fry until soft|Fry onion until golden brown|Add masala paste, tamarind, spices|Add fried brinjals to the gravy|Simmer until oil separates and gravy is rich|Temper with mustard, cumin, curry leaves' },
  { slug:'ulavacharu', name:'Ulavacharu', hi:'उलवाचारू', mr:'उलवाचारू', c:'andhra', v:true, m:['lunch','dinner'], cal:200, acc:'steamed-rice', d:'medium', p:15, ck:30, desc:'Horse gram rasam — a protein-rich, peppery Andhra broth that is deeply warming.', ings:'Horse gram:0.5:cup,Tomato:2:pieces,Tamarind pulp:1:tbsp,Black pepper:1:tsp,Cumin seeds:1:tsp,Red chilli powder:1:tsp,Turmeric powder:0.25:tsp,Garlic:4:pieces,Curry leaves:8:pieces,Mustard seeds:1:tsp,Ghee:1:tbsp,Coriander leaves:2:tbsp,Salt:1:tsp', steps:'Soak and pressure cook horse gram until very soft|Strain the broth, reserve|Add tomato, tamarind, spices to broth|Simmer 15 minutes|Temper mustard, cumin, garlic, curry leaves in ghee|Add tempering to rasam|Garnish with coriander and serve as soup or with rice' },
  { slug:'pesara-pappu', name:'Pesara Pappu', hi:'पेसर पप्पू', mr:'पेसर पप्पू', c:'andhra', v:true, m:['lunch','dinner'], cal:210, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Simple moong dal with an Andhra-style mustard-curry leaf tempering — clean, everyday lentils.', ings:'Moong dal:1:cup,Turmeric powder:0.5:tsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Dried red chillies:2:pieces,Curry leaves:8:pieces,Green chillies:2:pieces,Garlic:3:pieces,Ghee:2:tbsp,Salt:1:tsp', steps:'Wash and pressure cook moong dal with turmeric|Mash lightly|Temper mustard, cumin, dried chillies, garlic, curry leaves in ghee|Add green chillies|Pour over dal, mix|Serve with rice and ghee' },
  { slug:'veg-biryani-hyderabadi', name:'Hyderabadi Veg Biryani', hi:'हैदराबादी वेज बिरयानी', mr:'हैदराबादी वेज बिर्याणी', c:'andhra', v:true, m:['lunch','dinner'], cal:420, acc:null, d:'medium', p:20, ck:35, desc:'Layered vegetable and rice dum biryani — the vegetarian version of the Hyderabadi classic.', ings:'Basmati rice:2:cup,Mixed vegetables:2:cup,Onion:3:pieces,Yogurt:0.5:cup,Ginger:1:pieces,Garlic:4:pieces,Green chillies:4:pieces,Mint leaves:0.5:cup,Coriander leaves:0.5:cup,Saffron:0.25:tsp,Milk:0.25:cup,Ghee:3:tbsp,Oil:2:tbsp,Biryani masala:2:tbsp,Salt:1:tsp', steps:'Par-cook rice to 70%|Cook vegetables with yogurt, ginger-garlic, biryani masala|Fry onions until golden|Layer: vegetables, rice, fried onions, herbs|Pour saffron milk over top|Seal with dough, cook on low heat 25 minutes|Rest 10 minutes before serving' },
  { slug:'bendakaya-pulusu', name:'Bendakaya Pulusu', hi:'भिंडी पुलुसू', mr:'भेंडी पुलुसू', c:'andhra', v:true, m:['lunch','dinner'], cal:190, acc:'steamed-rice', d:'easy', p:10, ck:20, desc:'Okra in a tangy tamarind gravy — a sour, spicy Andhra-style curry.', ings:'Okra:300:g,Onion:1:pieces,Tamarind pulp:2:tbsp,Red chilli powder:1:tsp,Turmeric powder:0.25:tsp,Coriander powder:1:tsp,Mustard seeds:1:tsp,Fenugreek seeds:0.25:tsp,Curry leaves:8:pieces,Oil:3:tbsp,Salt:1:tsp,Jaggery:0.5:tsp', steps:'Slit and fry okra until crisp|Heat oil, add mustard, fenugreek, curry leaves|Add onion, cook until soft|Add tamarind water with spices|Bring to boil, add jaggery|Add fried okra to the gravy|Simmer 5 minutes until flavors meld' },

  // ===== PUNJABI (15) =====
  { slug:'sarson-ka-saag', name:'Sarson Ka Saag', hi:'सरसों का साग', mr:'सरसों का साग', c:'punjabi', v:true, m:['lunch','dinner'], cal:280, acc:'roti', d:'medium', p:20, ck:40, desc:'Slow-cooked mustard greens with spinach and bathua, mashed and finished with butter — Punjab\'s winter soul food.', ings:'Mustard greens:500:g,Spinach:200:g,Onion:1:pieces,Ginger:1:pieces,Garlic:4:pieces,Green chillies:3:pieces,Cornmeal:2:tbsp,Ghee:3:tbsp,Salt:1:tsp', steps:'Wash and chop mustard greens and spinach|Pressure cook greens with water until very soft|Blend coarsely with hand blender|Add cornmeal, cook on low stirring for 20 minutes|Sauté onion, ginger, garlic in ghee|Mix into saag|Serve with makki di roti and white butter' },
  { slug:'amritsari-chole', name:'Amritsari Chole', hi:'अमृतसरी छोले', mr:'अमृतसरी छोले', c:'punjabi', v:true, m:['lunch','dinner'], cal:340, acc:'roti', d:'medium', p:480, ck:30, desc:'Dark, richly spiced chickpea curry with tea-bag for color — the Amritsar dhaba classic.', ings:'Chickpeas:2:cup,Onion:2:pieces,Tomato:2:pieces,Ginger:2:pieces,Green chillies:3:pieces,Chole masala:2:tbsp,Amchur:1:tsp,Red chilli powder:1:tsp,Pomegranate powder:1:tsp,Bay leaves:1:pieces,Tea bags:1:pieces,Oil:3:tbsp,Salt:1:tsp', steps:'Soak chickpeas overnight with baking soda|Pressure cook with tea bag for dark color|Remove tea bag|Fry onion until deep brown|Add ginger, tomato, all spice powders|Cook until oil separates|Add chickpeas with their water|Simmer 15 minutes until thick and dark' },
  { slug:'tandoori-chicken', name:'Tandoori Chicken', hi:'तंदूरी चिकन', mr:'तंदूरी चिकन', c:'punjabi', v:false, m:['dinner'], cal:320, acc:null, d:'medium', p:240, ck:25, desc:'Yogurt and spice-marinated chicken roasted until charred — the iconic Punjabi dish that conquered the world.', ings:'Chicken (bone-in):1:kg,Yogurt:1:cup,Lemon juice:2:tbsp,Ginger:2:pieces,Garlic:6:pieces,Red chilli powder:2:tsp,Garam masala:1:tsp,Kashmiri red chillies:2:tsp,Oil:2:tbsp,Salt:1:tsp', steps:'Make deep cuts in chicken pieces|First marinate with lemon juice and salt for 30 minutes|Mix yogurt with all spices, ginger-garlic paste|Coat chicken in yogurt marinade|Refrigerate minimum 4 hours, overnight is best|Cook in very hot oven or grill at 220°C for 20-25 minutes|Baste with oil or butter, char slightly|Serve with onion rings and green chutney' },
  { slug:'dal-fry', name:'Dal Fry', hi:'दाल फ्राई', mr:'डाळ फ्राय', c:'punjabi', v:true, m:['lunch','dinner'], cal:240, acc:'steamed-rice', d:'easy', p:10, ck:25, desc:'Toor and masoor dal with a rich tomato-onion-garlic tadka — the dhaba staple found across India.', ings:'Toor dal:0.5:cup,Masoor dal:0.5:cup,Onion:1:pieces,Tomato:2:pieces,Garlic:4:pieces,Ginger:1:pieces,Green chillies:2:pieces,Cumin seeds:1:tsp,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Ghee:2:tbsp,Coriander leaves:2:tbsp,Salt:1:tsp', steps:'Wash and pressure cook both dals with turmeric|Mash well|Heat ghee, add cumin seeds|Add garlic, ginger, onion — fry until golden|Add tomatoes, cook until soft|Add chilli powder, salt|Pour in cooked dal, simmer 10 minutes|Garnish with coriander and green chillies' },
  { slug:'aloo-paratha-punjabi', name:'Aloo Paratha', hi:'आलू पराठा', mr:'आलू पराठा', c:'punjabi', v:true, m:['breakfast','lunch'], cal:350, acc:null, d:'easy', p:20, ck:15, desc:'Stuffed potato flatbread cooked with butter — the undisputed king of Punjabi breakfast.', ings:'Wheat flour:2:cup,Potato:3:pieces,Green chillies:3:pieces,Ginger:1:pieces,Coriander leaves:2:tbsp,Cumin seeds:1:tsp,Amchur:0.5:tsp,Red chilli powder:0.5:tsp,Ghee:3:tbsp,Salt:1:tsp', steps:'Knead wheat flour into soft dough|Boil and mash potatoes with chillies, ginger, spices, coriander|Make balls of dough, flatten|Place potato stuffing in center, seal and roll carefully|Cook on hot tawa with ghee on both sides|Press edges to cook evenly|Serve with yogurt, pickle and butter' },
  { slug:'paneer-tikka-punjabi', name:'Paneer Tikka', hi:'पनीर टिक्का', mr:'पनीर टिक्का', c:'punjabi', v:true, m:['dinner'], cal:320, acc:null, d:'medium', p:30, ck:15, desc:'Marinated paneer and vegetables chargrilled or oven-roasted — the vegetarian tandoori icon.', ings:'Paneer:300:g,Capsicum:1:pieces,Onion:2:pieces,Yogurt:0.5:cup,Red chilli powder:1:tsp,Garam masala:0.5:tsp,Kashmiri chilli:1:tsp,Lemon juice:1:tbsp,Ginger:1:pieces,Garlic:3:pieces,Oil:2:tbsp,Salt:1:tsp,Chaat masala:0.5:tsp', steps:'Cube paneer, capsicum, onion into large pieces|Mix yogurt with all spices, ginger-garlic, oil|Marinate paneer and vegetables for 30 minutes|Thread onto skewers|Grill or bake at 220°C for 12-15 minutes turning once|Sprinkle chaat masala and lemon juice|Serve with mint chutney' },
  { slug:'achari-paneer', name:'Achari Paneer', hi:'अचारी पनीर', mr:'अचारी पनीर', c:'punjabi', v:true, m:['lunch','dinner'], cal:340, acc:'roti', d:'medium', p:15, ck:20, desc:'Paneer in a tangy pickle-spiced gravy with fenugreek, mustard, and fennel — bold flavors.', ings:'Paneer:250:g,Onion:2:pieces,Tomato:2:pieces,Yogurt:0.5:cup,Mustard seeds:1:tsp,Fennel seeds:1:tsp,Fenugreek seeds:0.5:tsp,Cumin seeds:1:tsp,Red chilli powder:1:tsp,Turmeric powder:0.5:tsp,Oil:3:tbsp,Salt:1:tsp,Coriander leaves:2:tbsp', steps:'Cube and lightly fry paneer, set aside|Heat oil, add all whole seeds together|Add onion, cook until golden|Add tomato, cook until pulpy|Add spice powders and whisked yogurt on low heat|Add paneer cubes|Simmer 5 minutes until gravy coats paneer|Garnish with coriander' },
  { slug:'malai-kofta', name:'Malai Kofta', hi:'मलाई कोफ्ता', mr:'मलाई कोफ्ता', c:'punjabi', v:true, m:['dinner'], cal:420, acc:'naan', d:'hard', p:25, ck:30, desc:'Fried paneer-potato balls in a rich, creamy tomato gravy — the ultimate Punjabi restaurant classic.', ings:'Paneer:200:g,Potato:2:pieces,Cornstarch:2:tbsp,Cashew nuts:15:pieces,Onion:2:pieces,Tomato:3:pieces,Cream:0.5:cup,Ginger:1:pieces,Garlic:4:pieces,Garam masala:1:tsp,Red chilli powder:0.5:tsp,Turmeric powder:0.25:tsp,Sugar:1:tsp,Oil:4:tbsp,Salt:1:tsp,Dried fenugreek leaves:1:tbsp', steps:'Mash paneer and boiled potato, mix with cornstarch|Shape into balls, deep fry until golden|Soak and grind cashews into paste|Fry onion, add ginger-garlic|Add tomatoes, cook until soft, blend smooth|Return gravy to pan, add cashew paste, cream|Add sugar, spices, kasuri methi|Drop in koftas just before serving — they soften in gravy' },
  { slug:'tawa-chicken', name:'Tawa Chicken', hi:'तवा चिकन', mr:'तवा चिकन', c:'punjabi', v:false, m:['dinner'], cal:380, acc:'roti', d:'medium', p:15, ck:20, desc:'Chicken cooked on a flat griddle with onions, peppers, and bold spices — a dhaba favourite.', ings:'Chicken (bone-in):500:g,Onion:2:pieces,Capsicum:1:pieces,Tomato:2:pieces,Yogurt:3:tbsp,Ginger:1:pieces,Garlic:4:pieces,Red chilli powder:1.5:tsp,Garam masala:1:tsp,Coriander powder:1:tsp,Oil:3:tbsp,Butter:2:tbsp,Salt:1:tsp,Coriander leaves:2:tbsp,Lemon juice:1:tbsp', steps:'Marinate chicken with yogurt, ginger-garlic, spices|Heat oil and butter on tawa or flat pan|Sear chicken pieces until browned|Add sliced onion and capsicum|Add tomato, cook until chicken is done|Squeeze lemon, add coriander|Serve sizzling from the tawa' },
  { slug:'fish-amritsari', name:'Amritsari Fish', hi:'अमृतसरी फिश', mr:'अमृतसरी फिश', c:'punjabi', v:false, m:['dinner'], cal:340, acc:null, d:'easy', p:30, ck:10, desc:'Crispy beer-battered fish fillets with ajwain — Amritsar\'s legendary fried fish.', ings:'Fish fillets:500:g,Besan:0.5:cup,Rice flour:2:tbsp,Ajwain:1:tsp,Red chilli powder:1:tsp,Turmeric powder:0.25:tsp,Ginger:1:pieces,Garlic:4:pieces,Lemon juice:2:tbsp,Oil:4:tbsp,Salt:1:tsp', steps:'Cut fish into strips|Marinate with lemon juice, ginger-garlic, turmeric, salt|Make batter with besan, rice flour, ajwain, chilli|Dip fish strips in batter|Deep fry until golden and crispy|Serve hot with mint chutney and onion rings' },
  { slug:'shahi-paneer', name:'Shahi Paneer', hi:'शाही पनीर', mr:'शाही पनीर', c:'punjabi', v:true, m:['lunch','dinner'], cal:380, acc:'naan', d:'medium', p:15, ck:20, desc:'Paneer in a rich, creamy tomato-cashew gravy with a touch of saffron — Mughlai-Punjabi royalty.', ings:'Paneer:250:g,Onion:2:pieces,Tomato:3:pieces,Cashew nuts:10:pieces,Cream:0.5:cup,Saffron:0.25:tsp,Ginger:1:pieces,Garlic:3:pieces,Garam masala:1:tsp,Red chilli powder:0.5:tsp,Cardamom:2:pieces,Ghee:2:tbsp,Sugar:1:tsp,Salt:1:tsp', steps:'Sauté onion, add ginger-garlic, tomato|Soak and grind cashews|Blend onion-tomato into smooth paste|Cook paste in ghee with spices|Add cashew paste and cream|Add saffron soaked in milk|Add paneer cubes|Simmer gently 5 minutes' },
  { slug:'rajma-punjabi', name:'Punjabi Rajma', hi:'पंजाबी राजमा', mr:'पंजाबी राजमा', c:'punjabi', v:true, m:['lunch','dinner'], cal:340, acc:'steamed-rice', d:'easy', p:480, ck:30, desc:'Red kidney beans in a thick tomato-onion gravy — the ultimate Punjabi rajma chawal.', ings:'Red kidney beans:2:cup,Onion:2:pieces,Tomato:3:pieces,Ginger:2:pieces,Garlic:6:pieces,Red chilli powder:1:tsp,Coriander powder:1:tsp,Garam masala:1:tsp,Bay leaves:1:pieces,Oil:3:tbsp,Salt:1:tsp,Coriander leaves:2:tbsp', steps:'Soak rajma overnight|Pressure cook until completely soft|Fry onion until golden|Add ginger-garlic paste, cook|Add tomatoes, cook until pulpy|Add spice powders|Add rajma with their cooking liquid|Simmer 15-20 minutes until thick and creamy|Mash some beans for thickness' },
  { slug:'gobi-paratha', name:'Gobi Paratha', hi:'गोभी पराठा', mr:'गोभी पराठा', c:'punjabi', v:true, m:['breakfast','lunch'], cal:320, acc:null, d:'easy', p:15, ck:15, desc:'Cauliflower-stuffed flatbread — another Punjabi paratha classic after aloo paratha.', ings:'Wheat flour:2:cup,Cauliflower:300:g,Green chillies:3:pieces,Ginger:1:pieces,Cumin seeds:1:tsp,Coriander leaves:2:tbsp,Amchur:0.5:tsp,Red chilli powder:0.5:tsp,Ghee:3:tbsp,Salt:1:tsp', steps:'Knead dough with salt|Grate cauliflower, squeeze out moisture|Mix with chillies, ginger, spices, coriander|Roll dough, stuff with gobi filling|Seal and roll carefully|Cook on tawa with ghee until golden spots|Serve with yogurt, pickle, butter' },
  { slug:'kadhi-pakora-punjabi', name:'Punjabi Kadhi Pakora', hi:'पंजाबी कढ़ी पकोड़ा', mr:'पंजाबी कढी पकोडा', c:'punjabi', v:true, m:['lunch','dinner'], cal:300, acc:'steamed-rice', d:'medium', p:15, ck:30, desc:'Gram flour fritters dunked in a tangy yogurt-gram flour curry — thick, comforting, and addictive.', ings:'Yogurt:2:cup,Besan:0.5:cup,Onion:2:pieces,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Mustard seeds:1:tsp,Cumin seeds:1:tsp,Dried red chillies:2:pieces,Fenugreek seeds:0.25:tsp,Curry leaves:8:pieces,Ghee:2:tbsp,Salt:1:tsp,Baking soda:0.25:tsp', steps:'Make pakora batter with besan, onion, spices, baking soda|Deep fry pakoras until golden|Whisk yogurt with besan and water for kadhi|Cook kadhi on medium heat stirring until it boils|Add turmeric, chilli, salt|Simmer 20 minutes on low|Temper with mustard, cumin, fenugreek, curry leaves|Add pakoras to kadhi 10 minutes before serving' },

  // ===== NORTH INDIAN BREAKFAST (5) =====
  { slug:'poha', name:'Poha', hi:'पोहा', mr:'पोहे', c:'north', v:true, m:['breakfast'], cal:250, acc:null, d:'easy', p:5, ck:10, desc:'Flattened rice tossed with onion, peanuts, turmeric, and curry leaves — India\'s quickest breakfast.', ings:'Flattened rice:2:cup,Onion:1:pieces,Potato:1:pieces,Peanuts:2:tbsp,Green chillies:2:pieces,Curry leaves:8:pieces,Mustard seeds:1:tsp,Turmeric powder:0.5:tsp,Lemon juice:1:tbsp,Oil:2:tbsp,Salt:0.5:tsp,Sugar:0.5:tsp,Coriander leaves:2:tbsp', steps:'Rinse poha briefly, drain|Heat oil, add mustard, peanuts, curry leaves|Add onion, potato, green chillies|Cook until potato is tender|Add drained poha, turmeric, salt, sugar|Toss gently on low heat 2 minutes|Squeeze lemon, garnish with coriander' },
  { slug:'chole-bhature', name:'Chole Bhature', hi:'छोले भटूरे', mr:'छोले भटूरे', c:'north', v:true, m:['breakfast','lunch'], cal:480, acc:null, d:'medium', p:480, ck:25, desc:'Spicy chickpea curry with puffy deep-fried bread — the Delhi breakfast indulgence.', ings:'Chickpeas:2:cup,Maida:2:cup,Yogurt:3:tbsp,Onion:2:pieces,Tomato:2:pieces,Ginger:1:pieces,Tea bags:1:pieces,Chole masala:2:tbsp,Red chilli powder:1:tsp,Oil:4:tbsp,Salt:1:tsp,Baking soda:0.5:tsp', steps:'Soak chickpeas overnight, cook with tea bag until soft|Make chole: fry onion, add tomato, ginger, spices|Add chickpeas, simmer until thick|Knead maida with yogurt, oil, baking soda into dough|Rest 2 hours|Roll and deep fry until puffed and golden|Serve with pickled onion and green chutney' },
  { slug:'moong-dal-cheela', name:'Moong Dal Cheela', hi:'मूंग दाल चीला', mr:'मूग डाळ चीला', c:'north', v:true, m:['breakfast'], cal:200, acc:null, d:'easy', p:240, ck:10, desc:'Savory moong dal crepes — a protein-rich, gluten-free Indian breakfast.', ings:'Moong dal:1:cup,Ginger:1:pieces,Green chillies:2:pieces,Cumin seeds:0.5:tsp,Turmeric powder:0.25:tsp,Oil:2:tbsp,Salt:0.5:tsp,Onion:1:pieces', steps:'Soak moong dal 4 hours, grind into smooth batter|Add ginger, chillies, cumin, turmeric, salt|Pour ladle of batter on hot tawa, spread thin|Add chopped onion on top|Drizzle oil around edges|Cook until crispy, flip briefly|Serve with green chutney' },
  { slug:'besan-cheela', name:'Besan Cheela', hi:'बेसन चीला', mr:'बेसन चिला', c:'north', v:true, m:['breakfast'], cal:220, acc:null, d:'easy', p:5, ck:10, desc:'Quick gram flour pancakes with vegetables — no soaking needed, ready in minutes.', ings:'Besan:1:cup,Onion:1:pieces,Tomato:1:pieces,Green chillies:2:pieces,Cumin seeds:0.5:tsp,Ajwain:0.25:tsp,Coriander leaves:2:tbsp,Oil:2:tbsp,Salt:0.5:tsp,Water:0.75:cup', steps:'Mix besan with water into thin batter|Add finely chopped onion, tomato, chillies, coriander|Add cumin, ajwain, salt|Pour on hot tawa, spread thin|Cook with oil until golden on both sides|Serve with ketchup or green chutney' },
  { slug:'stuffed-paratha', name:'Mixed Veg Paratha', hi:'मिक्स वेज पराठा', mr:'मिक्स वेज पराठा', c:'north', v:true, m:['breakfast','lunch'], cal:330, acc:null, d:'easy', p:20, ck:15, desc:'Flatbread stuffed with a mix of grated vegetables and spices — versatile breakfast or lunch.', ings:'Wheat flour:2:cup,Carrot:1:pieces,Cabbage:1:cup,Capsicum:0.5:pieces,Onion:1:pieces,Green chillies:2:pieces,Ginger:1:pieces,Cumin seeds:1:tsp,Red chilli powder:0.5:tsp,Ghee:3:tbsp,Salt:1:tsp,Coriander leaves:2:tbsp', steps:'Knead dough with salt|Grate carrot, finely chop cabbage, capsicum, onion|Mix vegetables with chillies, ginger, spices|Squeeze out excess moisture|Roll dough, stuff with veg filling, seal and roll|Cook on tawa with ghee until golden spots|Serve with yogurt and pickle' },

  // ===== MARATHI BREAKFAST (5) =====
  { slug:'misal-pav', name:'Misal Pav', hi:'मिसल पाव', mr:'मिसळ पाव', c:'marathi', v:true, m:['breakfast','lunch'], cal:350, acc:null, d:'medium', p:480, ck:20, desc:'Sprouted moth beans curry topped with farsan, onion, and lemon — fiery Maharashtrian breakfast.', ings:'Moth beans:1:cup,Onion:2:pieces,Tomato:1:pieces,Coconut:2:tbsp,Goda masala:1:tbsp,Red chilli powder:1.5:tsp,Turmeric powder:0.5:tsp,Mustard seeds:1:tsp,Curry leaves:8:pieces,Oil:3:tbsp,Pav bread:4:pieces,Farsan:0.5:cup,Salt:1:tsp,Lemon juice:1:tbsp', steps:'Soak moth beans overnight, cook until tender|Make kat (gravy): fry onion, add tomato, spices, coconut|Add cooked beans to gravy|Temper with mustard and curry leaves|Serve in bowl topped with chopped onion, farsan, lemon|Side with buttered pav' },
  { slug:'sabudana-khichdi', name:'Sabudana Khichdi', hi:'साबूदाना खिचड़ी', mr:'साबुदाणा खिचडी', c:'marathi', v:true, m:['breakfast'], cal:300, acc:null, d:'easy', p:480, ck:10, desc:'Sago pearls tossed with peanuts, potato, and cumin — a Maharashtrian fasting breakfast favourite.', ings:'Sago pearls:1:cup,Peanuts:0.5:cup,Potato:2:pieces,Green chillies:3:pieces,Cumin seeds:1:tsp,Curry leaves:6:pieces,Lemon juice:1:tbsp,Oil:2:tbsp,Sugar:0.5:tsp,Salt:0.5:tsp,Coriander leaves:2:tbsp', steps:'Soak sago overnight until soft and separated|Roast and coarsely crush peanuts|Cube and fry potato until golden|Heat oil, add cumin, curry leaves, green chillies|Add sago, peanuts, potato|Toss on low heat until sago turns translucent|Add sugar, salt, lemon juice, coriander' },
  { slug:'pohe-marathi', name:'Kanda Pohe', hi:'कांदा पोहा', mr:'कांदा पोहे', c:'marathi', v:true, m:['breakfast'], cal:240, acc:null, d:'easy', p:5, ck:10, desc:'The Maharashtrian version of poha with plenty of onion, a touch of sugar, and fresh coconut garnish.', ings:'Flattened rice:2:cup,Onion:2:pieces,Potato:1:pieces,Peanuts:2:tbsp,Green chillies:2:pieces,Mustard seeds:1:tsp,Turmeric powder:0.5:tsp,Curry leaves:8:pieces,Lemon juice:1:tbsp,Oil:2:tbsp,Sugar:1:tsp,Salt:0.5:tsp,Coconut:2:tbsp,Coriander leaves:2:tbsp', steps:'Rinse poha, drain and set aside|Heat oil, add mustard seeds, peanuts|Add curry leaves, onion, green chillies|Add potato, cook until soft|Add poha, turmeric, salt, sugar|Toss gently on low heat|Squeeze lemon, top with coconut and coriander' },
  { slug:'kothimbir-vadi', name:'Kothimbir Vadi', hi:'कोथिंबीर वड़ी', mr:'कोथिंबीर वडी', c:'marathi', v:true, m:['breakfast'], cal:180, acc:null, d:'medium', p:15, ck:20, desc:'Steamed coriander-gram flour cakes, sliced and fried until crispy — a Maharashtrian tea-time snack.', ings:'Coriander leaves:2:cup,Besan:1:cup,Sesame seeds:1:tbsp,Green chillies:2:pieces,Ginger:1:pieces,Turmeric powder:0.25:tsp,Ajwain:0.5:tsp,Oil:3:tbsp,Salt:0.5:tsp', steps:'Finely chop coriander leaves|Mix with besan, sesame, spices, ginger, chillies|Add water to make thick batter|Spread on greased plate, steam 15 minutes|Cool, cut into squares or diamonds|Shallow fry until crispy on both sides' },
  { slug:'batata-vada-marathi', name:'Batata Vada', hi:'बटाटा वड़ा', mr:'बटाटा वडा', c:'marathi', v:true, m:['breakfast','lunch'], cal:300, acc:'pav', d:'easy', p:15, ck:10, desc:'Spiced mashed potato balls coated in gram flour batter and deep fried — the OG vada pav filling.', ings:'Potato:4:pieces,Besan:1:cup,Green chillies:3:pieces,Ginger:1:pieces,Garlic:3:pieces,Mustard seeds:1:tsp,Curry leaves:8:pieces,Turmeric powder:0.5:tsp,Oil:4:tbsp,Salt:0.5:tsp,Coriander leaves:2:tbsp', steps:'Boil and mash potatoes|Temper mustard, curry leaves, add ginger-garlic-chilli paste|Mix into potatoes with turmeric, salt, coriander|Shape into balls|Make thin batter with besan, turmeric, salt, water|Dip balls in batter|Deep fry until golden and crispy|Serve with pav and chutneys' },

  // ===== BIHARI BREAKFAST (4) =====
  { slug:'chura-matar', name:'Chura Matar', hi:'चूड़ा मटर', mr:'चुरा मटार', c:'bihari', v:true, m:['breakfast'], cal:280, acc:null, d:'easy', p:5, ck:10, desc:'Flattened rice with green peas — Bihar\'s hearty winter morning breakfast, quick and filling.', ings:'Flattened rice:2:cup,Green peas:1:cup,Onion:1:pieces,Green chillies:2:pieces,Mustard oil:2:tbsp,Cumin seeds:1:tsp,Turmeric powder:0.25:tsp,Salt:0.5:tsp,Sugar:0.5:tsp,Lemon juice:1:tbsp', steps:'Rinse flattened rice, drain|Heat mustard oil, add cumin seeds|Add onion, green chillies|Add peas, cook 3 minutes|Add poha, turmeric, salt, sugar|Toss on low heat 2 minutes|Squeeze lemon and serve' },
  { slug:'sattu-paratha-bihari', name:'Sattu Paratha', hi:'सत्तू पराठा', mr:'सत्तू पराठा', c:'bihari', v:true, m:['breakfast','lunch'], cal:320, acc:null, d:'easy', p:15, ck:15, desc:'Wheat flatbread stuffed with spiced roasted gram flour — protein-packed Bihari breakfast, filling and nutritious.', ings:'Wheat flour:2:cup,Sattu:1:cup,Onion:1:pieces,Green chillies:3:pieces,Ginger:1:pieces,Ajwain:0.5:tsp,Mustard oil:3:tbsp,Lemon juice:1:tbsp,Salt:1:tsp', steps:'Mix sattu with chopped onion, chillies, ginger|Add mustard oil, lemon juice, salt|Knead wheat flour into soft dough|Roll dough, stuff with sattu filling|Seal and roll gently|Cook on tawa with oil or ghee until golden|Serve with chutney or pickle' },
  { slug:'makhana-curry', name:'Makhana Curry', hi:'मखाना करी', mr:'मखाना करी', c:'bihari', v:true, m:['lunch','dinner'], cal:280, acc:'roti', d:'easy', p:10, ck:20, desc:'Fox nuts in a creamy onion-tomato gravy — a Bihari/Mithila specialty that\'s light yet rich.', ings:'Fox nuts:2:cup,Onion:2:pieces,Tomato:2:pieces,Ginger:1:pieces,Green chillies:2:pieces,Cream:0.25:cup,Turmeric powder:0.5:tsp,Red chilli powder:0.5:tsp,Garam masala:0.5:tsp,Oil:2:tbsp,Salt:1:tsp,Coriander leaves:2:tbsp', steps:'Roast fox nuts in a dry pan until crispy|Fry onion until golden|Add ginger, tomato, cook until pulpy|Add turmeric, chilli, garam masala|Add water, bring to simmer|Add roasted makhana|Cook 5 minutes, add cream|Garnish with coriander' },
  { slug:'baingan-chokha', name:'Baingan Chokha', hi:'बैंगन चोखा', mr:'वांग्याचे चोखा', c:'bihari', v:true, m:['lunch','dinner'], cal:150, acc:'roti', d:'easy', p:10, ck:15, desc:'Smoky roasted brinjal mash with mustard oil, raw onion, and green chillies — rustic Bihari soul food.', ings:'Brinjal:2:pieces,Mustard oil:2:tbsp,Onion:1:pieces,Green chillies:3:pieces,Garlic:3:pieces,Salt:0.5:tsp,Coriander leaves:2:tbsp,Lemon juice:1:tbsp', steps:'Roast whole brinjals over direct flame until charred and soft|Peel off charred skin|Mash the smoky flesh|Mix with finely chopped onion, green chillies, garlic|Add mustard oil, salt, lemon juice|Garnish with coriander|Serve with litti or roti' },
]

async function run() {
  console.log(`Processing ${dishes.length} dishes...`)

  // Collect unique ingredients
  const ingMap = new Map()
  for (const d of dishes) {
    for (const raw of d.ings.split(',')) {
      const [name, qty, unit] = raw.split(':')
      if (!ingMap.has(name.trim())) ingMap.set(name.trim(), { name_en: name.trim(), category: 'pantry', default_unit: unit?.trim() || 'pieces' })
    }
  }

  // Upsert ingredients (English only — translations added later)
  const ingRows = Array.from(ingMap.values()).map(i => ({
    name_en: i.name_en, name_hi: null, name_mr: null, category: i.category, default_unit: i.default_unit,
  }))
  const { error: ie } = await supabase.from('ingredients').upsert(ingRows, { onConflict: 'name_en', ignoreDuplicates: true })
  if (ie) console.error('Ing error:', ie.message)
  else console.log(`✓ ${ingRows.length} ingredients upserted`)

  // Fetch ingredient IDs
  const { data: allIngs } = await supabase.from('ingredients').select('id, name_en')
  const ingIdMap = new Map(allIngs.map(i => [i.name_en, i.id]))

  // Insert dishes
  let ok = 0
  for (const d of dishes) {
    const row = {
      slug: d.slug, name_en: d.name, name_hi: d.hi, name_mr: d.mr, cuisine: d.c,
      is_veg: d.v, meal_types: d.m, prep_time_min: d.p || null, cook_time_min: d.ck || null,
      difficulty: d.d || 'easy', default_servings: 2, default_accompaniment: d.acc || null,
      calories: d.cal, protein_g: null, carbs_g: null, fat_g: null, fiber_g: null,
      description_en: d.desc, description_hi: null, description_mr: null,
      youtube_url: `https://www.youtube.com/results?search_query=${encodeURIComponent(d.name + ' recipe')}`,
      is_custom: false,
    }
    const { error } = await supabase.from('dishes').upsert(row, { onConflict: 'slug', ignoreDuplicates: true })
    if (error) console.error(`  ${d.slug}: ${error.message}`)
    else ok++
  }
  console.log(`✓ ${ok}/${dishes.length} dishes inserted`)

  // Fetch dish IDs
  const { data: allD } = await supabase.from('dishes').select('id, slug')
  const dishIdMap = new Map(allD.map(d => [d.slug, d.id]))

  // Insert dish_ingredients
  let diCount = 0
  for (const d of dishes) {
    const dishId = dishIdMap.get(d.slug)
    if (!dishId) continue
    const rows = d.ings.split(',').map(raw => {
      const [name, qty, unit] = raw.split(':')
      const ingId = ingIdMap.get(name.trim())
      if (!ingId) return null
      return { dish_id: dishId, ingredient_id: ingId, quantity: parseFloat(qty) || 1, unit: unit?.trim() || 'pieces' }
    }).filter(Boolean)
    if (rows.length) {
      const { error } = await supabase.from('dish_ingredients').insert(rows)
      if (error) console.error(`  DI ${d.slug}: ${error.message}`)
      else diCount += rows.length
    }
  }
  console.log(`✓ ${diCount} dish_ingredients inserted`)

  // Insert recipe_steps (English only)
  let stepCount = 0
  for (const d of dishes) {
    const dishId = dishIdMap.get(d.slug)
    if (!dishId) continue
    const rows = d.steps.split('|').map((step, i) => ({
      dish_id: dishId, step_number: i + 1,
      instruction_en: step.trim(), instruction_hi: null, instruction_mr: null, duration_min: null,
    }))
    if (rows.length) {
      const { error } = await supabase.from('recipe_steps').insert(rows)
      if (error) console.error(`  Steps ${d.slug}: ${error.message}`)
      else stepCount += rows.length
    }
  }
  console.log(`✓ ${stepCount} recipe_steps inserted`)

  // Final counts
  const counts = await Promise.all([
    supabase.from('dishes').select('id', { count: 'exact', head: true }),
    supabase.from('ingredients').select('id', { count: 'exact', head: true }),
    supabase.from('recipe_steps').select('id', { count: 'exact', head: true }),
    supabase.from('dish_ingredients').select('id', { count: 'exact', head: true }),
  ])
  console.log(`\nFinal: ${counts[0].count} dishes, ${counts[1].count} ingredients, ${counts[2].count} steps, ${counts[3].count} dish_ingredients`)
}

run().catch(console.error)
